name: Android CI

env:
  # The name of the main module repository
  main_project_module: app

permissions: {}

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'corretto'
        cache: 'gradle'

    - name: Create base64 jks file
      run: echo "${{ secrets.BASE_64_SIGNING_KEY }}" > app/release_keystore.txt

    - name: Create jks file
      run: base64 -d "app/release_keystore.txt" > app/release_keystore.jks

    - name: Create Blank Local Properties File
      run: touch local.properties

    - name: Create Keystore Properties File
      run: echo "${{ secrets.LOCAL_PROPERTIES }}" > keystore.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set current date as env variable
      run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    # Standard Release Build Task
    - name: Build apk release project (APK)
      run: ./gradlew :${{ env.main_project_module }}:assembleRelease --warning-mode all

    # Upload All Release APKs (chahe universal ho ya arm64/v7a ABI splits)
    - name: Upload All Release APKs
      uses: actions/upload-artifact@v4
      with:
        name: App-Release-APKs
        path: ${{ env.main_project_module }}/build/outputs/apk/release/
        if-no-files-found: error

    # Send Message To Telegram
    - name: send telegram message on push or pull
      continue-on-error: true
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }}
          Repository: ${{ github.repository }}
          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
